### ISSUE TITLE
Fix file globbing with win (e.g mingw64) and add test for appveyor

### ISSUE THREAD

**Issue by philsmd** [hashcat/hashcat#1032]
We recently saw here (https://github.com/hashcat/hashcat/pull/1024, thanks @stephengroat)  that tests with appveyor would be a nice test addition.
Furthermore, we recently found out that appveyor does in fact report some problems even with the latest hashcat version (https://github.com/hashcat/hashcat/pull/1031#issuecomment-278268781).

Therefore I suggest:

1. we add the .appveyor.yml file (similar to the one here: https://github.com/hashcat/hashcat/pull/1024) and sign up for appveyor test builds
2. we test the appveyor buids and fix the file globbing problems
3. we fix all additional problems that appveyor might report
4. add the appveyor badges to README.md
5. we should add some hashcat-run tests (preferably to the appveyor tests, if possible) to check if the globbing really works (like hashcat -m 0 --show *ple0.hash, it should expand the name to example0.hash and if globbing didn't work the exit code should be different from 0)

Maybe you, @neheb, could have a look at this issue? You seem to grasp the problem with file globbing and the different environments that we need to test (cygwin/mingw/mysys etc) more than anyone else here.
Thanks

---

I would suggest that the person that tries to implement all of this,  #signs up (with his/her own account) to appveyor and links his/her test results here. If everything seems good and after merging, this github user ("hashcat") should sign up too and link the master branch + add the badges to the README.md

**Comment by neheb** [comment]
I'll need to test this again but I believe the MinGW shortcuts provided by MSYS2 change environment variables to help out configure scripts find the right binaries.

Now, that's important to mention since the hashcat makefile just selects standard GCC under the MinGW environment and compiles a standard POSIX binary.

I can't say I want to work on this since I'm not an MSYS2 user. They both have different use cases.

**Comment by stephengroat** [comment]
i was still modifying my appveyor script, i can start a new pull request and allow both maintainers and anyone interested to edit

the only problem that i currently see if that msys 64bit builds currently fail because they find the i686 `CRT_glob.o`.

I think adding this to main removes the need to find the `.o`:
````c
#if defined(__MINGW64__) || defined(__MINGW32__)
int _dowildcard = -1; 
#endif
````

Quick question: how do you run tests? it's not just running tools/test.sh, right?

**Comment by philsmd** [comment]
I'm not sure about this _dowildcard variable... but  if it really works (and the binary builds - cross-compilations - continue to work), then we should make changes to reflect this new approach also in the win globbing file (win_file_globbing.mk).
Furthermore, I just found out that the mingw compiler allows this command line option: --enable-wildcard (which actually does something similar to _dowildcard = -1, but seems to be a little bit more intuitive).
We should definitevely document all this facts within win_file_globbing.mk:
1. on which systems (mingw native, mingw cross-compile, mysys, cygwin, .... you name it!) we can use file globbing
2. for each and every of this systems we should explain our approach: for instance in this case we could document it like this: "for mingw builds, we can simply use --enable-wildcard, no need to find CRT_glob.o" (this is just an example, I'm still not sure if this is correct, we need to test)
3. of course we also need to change win_file_globbing.mk accordingly (or in some cases it might be needed to also change src/Makefile)

---

For what regards the tests: when I was mentioning "hashcat-run tests" with appveyor I was thinking about some (or even just a single one to start with) very quick tests after appveyor finished the building process. Not a full run of tools/test.sh ! this would be much too demanding. tools/test.sh is intended to test each and every hash type, this takes hours.
Instead, I was thinking here about something similar to the "test" formula-sections which the hashcat.rb homebrew formula performs: just some quick tests after the build process.

I found out (already yesterday when opening this issue), that appveyor allows to do exactly this: see https://www.appveyor.com/docs/appveyor-yml/ (search for "test_script").

I'm not sure exactly what we need to write under that section, but it seems that it just tests for the exit code of the executable (is this correct?). Then it would be something as simple as this:
```
test_script:
  - hashcat -m 0 --show *ple0.hash
```
This would, if everything works correctly, return exit code 0 (and therefore succeed, because the file should expand to example0.hash)
Ideally, we would also test for the opposite (e.g. if we specify a file that shouldn't exit, it should throw an error e.g. "hashcat -m 0 --show *file_not_found.hash")

Btw: if needed I saw some more elaborate examples of appveyor.yml test_script section, see 
https://github.com/Microsoft/bond/blob/master/appveyor.yml#L213-L243 (just a random example, but the throw statements look interesting, I'm also still not sure if we can use this "ps" (powershell?) accross all windows builds with appveyor, this needs to be tested). Something that might be needed is using this: `if ($LastExitCode -ne 0) { $host.SetShouldExit ($LastExitCode)  } ` in case of the "opposite/failing globbing test" mentioned above etc, but this all needs to be double checked

---

Update: it seems that --enable-wildcard does something different than I was thinking it would do.... it is just used to compile the mingw libraries themself, not the end-user binaries with gcc (so it seems we can't use --enable-wildcard, even if that would be some really nice feature of mingw, but it doesn't work like I was thinking)

**Comment by jsteube** [comment]
Update:

After some tests I found out that there's actually no more need for glob.o when using the _dowildcard variable. For me this variable was unknown, which is the only reason why I've always used the glob.o instead.

I've tested cygwin, Msys2 and the cross-compilation from Linux. They all work fine, therefore I've also removed the win_file_globbing.mk include which makes the Makefile more easy to read.

I hope this will also simplify the process with the appveyor integration.

**Comment by philsmd** [comment]
btw, these are the changes that are important for this issue here too (and about which @jsteube is talking about): https://github.com/hashcat/hashcat/commit/79513ce2265f0541142a4f1ee8989db594ebe537

**Comment by stephengroat** [comment]
if i make a new pr with an appveyor branch and give anyone who's interested push access, could that be communally worked on? we could just leave it for awhile before merging

**Comment by jsteube** [comment]
@stephengroat I think the .yml PR was fine as it was before. All the other stuff has been dealt with. So if you create a new PR with just the .yml we can merge that.

**Comment by jsteube** [comment]
@stephengroat I've merged the .yml. Do you think we should add the appveyor badge to README.md as we do with the travis one? Can you please create a PR for that.

@stephengroat With your new PR you've changed the git submodule init behavior. While it's not problem related to this change, do you know who to tell travis to checkout the correct commit and not just the latest? We intentionally use an older version but travis seems to ignore this

**Comment by philsmd** [comment]
Just that we avoid doing the same thing: I'm currently preparing 2 commits for badges and for the "test_script" session (2 PRs should be ready soon).
After that we will see what is still missing to close this issue.

**Comment by philsmd** [comment]
What is still confusing to me is this:
```
MSYSTEM: MINGW32
BASH: C:\msys64\usr\bin\bash
MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
```

Why msys64 paths with MINGW32, is this even correct? mayeb you can explain, @stephengroat?

**Comment by jsteube** [comment]
@stephengroat @philsmd Guys, thanks for PR's!

**Comment by stephengroat** [comment]
@philsmd the `MSYSTEM` environment variable controls 32 or 64 bit compilation environments. the base machine is still a 64 bit, so that's why it's always run out of the msys64

**Comment by philsmd** [comment]
That was exactly what I was thinking about this strange inconsistency between paths vs MSYSTEM name (32 vs 64). Thanks for confirming it. I just wanted to make sure that we do not build 64bit mingw/msys binaries twice.
BTW: the .appveyor.yml should now be working with test_script(s) runs... hope you can confirm that the file looks good .... and thanks again for your contributions!
