### ISSUE TITLE
#bug: Reuse PBKDF2 intermediate keys if duplicate essid is detected broken

### ISSUE THREAD

**Issue by ZerBea** [hashcat/hashcat#1141]
After upgrade from v3.30-356-g3fb433de to v3.30-372-gd431874c reuse PBKDF2 intermediate keys is broken:

 v3.30-356-g3fb433de:
Speed.Dev.#1.....:  2048.4 kH/s (4.87ms)

v3.30-372-gd431874c
Speed.Dev.#1.....:   165.2 kH/s (4.91ms)

Same testfile, same wordlist....
Best regards
ZerBea

**Comment by jsteube** [comment]
There was actually a bug, I've fixed it with: https://github.com/hashcat/hashcat/commit/c47f9d4b3eddd25b79dee6e9562c4c9b2cd8fc03

However, there was another bug reported here: https://github.com/hashcat/hashcat/issues/1137

Which requires a code change which can affect reuse PBKDF2 intermediate keys cracking performance but ONLY for a short time and ONLY if it's cracking the first of N handshake with the same ESSID, which is a very rare event in real life cases. If it's not cracking, performance is not changed. See here:

1 handshake:

```
$ echo -n hashcat1 | tools/test.pl passthrough 2500 | base64 -d > test.hccapx 
$ ./hashcat -m 2500 test.hccapx -w 3 opencrack_plains.txt 
```
```
Status...........: Exhausted
Time.Started.....: Tue Feb 28 10:03:37 2017 (43 secs)
```

2 handshake:

```
$ echo -n hashcat1 | tools/test.pl passthrough 2500 | base64 -d >> test.hccapx 
$ ./hashcat -m 2500 test.hccapx -w 3 opencrack_plains.txt 
```
```
Status...........: Exhausted
Time.Started.....: Tue Feb 28 10:05:23 2017 (42 secs)
```

Please test the bugfix and close the issue if fixed.

**Comment by ZerBea** [comment]
Not fixed using v3.30-374-gc47f9d4b
Speed.Dev.#1.....:   166.9 kH/s (4.88ms)

**Comment by jsteube** [comment]
Did you test with non-cracking handshakes?

Am 28.02.2017 10:30 vorm. schrieb "ZerBea" <notifications@github.com>:

**Comment by ZerBea** [comment]
Yes, and no....
Ok. If there are non-cracking hashes inside, it works like you mentioned.
But if there is only 1 cracked hash inside, speed will drop and stay on this level......
Let's say, you have 100 different ap's inside the hccapx, using the same essid called "default" and
the used word list is about 1 GB.
The password for ten ore more ap's is them same "12345678"
Speed drops from 10 minutes to a day..... 
If you have a theoretically successrate obove 50 % and many ap's, using the same essid and the same easy pw's, this case happens very often.....

**Comment by jsteube** [comment]
I think the ETA is just invalid for a short time (when it's cracking a
handshake). Can you please try to do a full run and measure time it
actually takes?

**Comment by ZerBea** [comment]
No problem. I'll do some complete runs.....
It will take a time.....

**Comment by ZerBea** [comment]
First run:
v3.30-374-gc47f9d4b
Hashes: 6050728 digests; 146376 unique digests, 146376 unique salts
Small wordlist (21197 words)
all non-cracked
It seems to be ok, speed varies from 164.9 kH/s upt to 179 M/s.....
v3.30-372-gd431874c was constant on ~ 166 kH/s

**Comment by ZerBea** [comment]
First run complete:
Started: Tue Feb 28 11:06:51 2017
Stopped: Tue Feb 28 11:24:43 2017

**Comment by ZerBea** [comment]
Second run:
v3.30-356-g3fb433de (old version)
Started: Tue Feb 28 11:26:57 2017
Stopped: Tue Feb 28 11:44:59 2017

So far, so good.....

**Comment by ZerBea** [comment]
Third run:
v3.30-374-gc47f9d4b
we replace 905 not found pw's by found pw's......

**Comment by ZerBea** [comment]
Third run:
v3.30-374-gc47f9d4b
we replace 905 not found pw's by found pw's in our wordlist.....
passwords are picked up randomly......

Started: Tue Feb 28 12:11:02 2017
Stopped: Tue Feb 28 12:29:30 2017
As you can see, already in this simple case we lose half a minute against the first run (17: 52 vs 18:28).
That means, the better the success rate the slower hashcat (that's a big time loss and it behaves like an e-function....).

**Comment by jsteube** [comment]
Yeah but that's ok because most of the time you don't really crack something. Also this is a fixed time added for each crack. That means if you do a crack in the first minute but there's still 3 hours to crack, it will only take 3 hours not 3 hours +X. I think that's ok or?

**Comment by ZerBea** [comment]
Indeed, it's not a big problem and of course it's ok....
Man can do some presorting and everything will be fine.
I'll close this issue, because your fix did it (v3.30-374-gc47f9d4b). It works much better than v3.30-372-gd431874c.....
Again, great job, thank you for your effort.
