### ISSUE TITLE
Unicode folder names don't work in Windows

### ISSUE THREAD

**Issue by neheb** [hashcat/hashcat#1233]
Log:

C:\Users\mangix\Desktop\??????????\hashcat>hashcat.exe
Usage: hashcat.exe [options]... hash|hashfile|hccapxfile [dictionary|mask|directory]...

Try --help for more help.

C:\Users\mangix\Desktop\??????????\hashcat>hashcat.exe -b
hashcat (v3.5.0-18-g086a0726+) starting in benchmark mode...

C:\Users\mangix\Desktop\??????????\hashcat/benchmark.pid: Invalid argument

C:\Users\mangix\Desktop\??????????\hashcat/hashcat.hctune: Invalid argument

Started: Mon Apr 24 17:21:22 2017
Stopped: Mon Apr 24 17:21:22 2017

C:\Users\mangix\Desktop\??????????\hashcat>

**Comment by zza123** [comment]
Why does the situatiom appear?Can you solve it? Please help me

**Comment by neheb** [comment]
fopen fails since the path is UTF-16. Needs to be rewritten to use Windows APIs

**Comment by zza123** [comment]
How to use windows APIs?I am greenhand...

**Comment by jsteube** [comment]
I tried on linux with all kind of strange utf-8 characters, seems to works. So it's perhaps the zero byte in the utf-16 causing the problems.

**Comment by jsteube** [comment]
Since windows installations do not make use of "make install" we can switch back on windows to relative paths. I've pushed a fix for this issue with commit https://github.com/hashcat/hashcat/commit/8ec2af97ed6adeae0dab0cb479f13cdf3e2b0031

I've also add a new beta to https://hashcat.net/beta/

Please test if the issue is fixed and close it

**Comment by neheb** [comment]
I'm gonna close this just because I don't use unicode filenames. The original error is fixed.

Having said that, hashcat still cannot handle Unicode files under windows. Let's say you have a file with a unicode name. Hashcat will fail to open that with ??????.txt: No such file or directory

**Comment by neheb** [comment]
Update: https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#UTF-8

There are solutions there for getting this working.

Windows 10 also supports setting the codepage to UTF8 now. Microsoft also recommends doing this, which is hilarious.

**Comment by neheb** [comment]
Easiest way to fix this is to run "chcp 65001" in the windows shell before actually running hashcat.

**Comment by philsmd** [comment]
hmm, @neheb did you re-open this on purpose or was this just a misclick ?

I think it's good that microsoft/windows changed something here, but this is out of our control... It's good that it changed for the better (it seems).

I don't think we should/could do anything here.

As far as I understand it, is that any modern windows 10 system (with that update from **May 2019**) should have UTF8 as default encoding in cmd and powershell. That sounds good.

close this issue again or should we do something here?

**Comment by neheb** [comment]
No. UTF8 is not default. There's also the issue of previous versions of Windows.

**Comment by philsmd** [comment]
thanks for the answer @neheb. But there is still a thing that I don't understand: why did you reopen this github issue? did something change ? Do you thing we should and can change something in hashcat's code ? Any recommendation or solution ?

When I read the wiki and referenced links from microsoft: https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page

It sounds like it is default:
`With a minimum target version of Windows Version 1903, the process code page will always be UTF-8`

that sentence confused me and made me believe it's enabled by default (which would be great of course for us).

I think we need more info here to see if we should/can do something. Thx

**Comment by neheb** [comment]
To test this: run Windows 7 or 8 (or an old build of windows 10) and create a junk unicode folder to extract hashcat to.

cd with command prompt to that directory and run some hashcat workload. Maybe the examples included. fopen will fail.

The solution is to do chcp 65001 before running hashcat. Or use a windows API instead of fopen. Or run Windows 10 with the system UTF8 option enabled.

While this is not an issue with hashcat cygwin or msys2, it is an issue with the binaries distributed on the website.

**Comment by philsmd** [comment]
You didn't answer it directly, but I assume you are trying to say that newer versions of hashcat (including version 6.0.0) have this regression that utf8/unicode paths now fail again, while previous versions did work. In my opinion it could have to do with this: https://github.com/hashcat/hashcat/commit/dc9f4e993a64da8a98574f1ec85490a6bfbe6b39 (not sure about any other recent commit that changes any other path behaviour). Is this true ? Why didn't you mention this in the first place (that you see some regression, or at least the problem reappearing, while it was gone before ) ?

Can you programmatically set the default encoding to UTF8 very easily ? How to do that ? Doesn't the shell dictate the encoding that the programs need to use ? Could you just change it with an API call ? or do we need to change all our fopen () calls ?
The problem is that that would probably not be enough, since the OpenCL/CUDA compilers also need to work with the correct encoding... otherwise they will fail too (the OpenCL kernel compiler is an external tool, we can't really change it's behaviour... so we can't change fopen calls for include files and flags like -I / -L etc). I think just changing every file read/write function won't help here. we would need to have and change some global settings at program start, I guess.

**Comment by neheb** [comment]
No this was never fixed. I initially closed as I figured there was no real point to fixing.

**Comment by philsmd** [comment]
Maybe this is a stupid suggestion/idea, but something came to my mind right now:
what if we just add a hashcat wiki entry like https://hashcat.net/q/timeoutpatch and tell the user how they can set the encoding to UTF8 within there cmd.

I've now searched on the internet (and especially on github) for a while and it seems that we can't do much, except maybe 1. adding a warning message to hashcat IF windows was detected and maybe 2. if we can maybe perform a little "test" to see if utf8 encoding is enabled and maybe if files could be created and opened.

Could you maybe help us with the text for that wiki entry ?

We already got that info from you about the `chcp 65001` method, but this is not persistent I guess.
We would also need to understand if the user would need to be admin or have priviledged permissions to do this (`chcp 65001`).

I also saw somebody doing some registry hacks or add startup jobs that do this change. Maybe we could also suggest that in the wiki.

For instance, I found this method: https://github.com/PowerShell/PowerShell/issues/7233#issuecomment-640243647 (actually 2 options).

or this: https://github.com/PowerShell/PowerShell/issues/7233#issuecomment-640081037

or this: https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8/927575#927575


some guys (https://github.com/PowerShell/PowerShell/issues/7233#issuecomment-640081037) warn also that the font size within the powershell change when doing some registry modifications:
`it seems to lock PowerShell into a small font size`

I have no clue if this is (still) true and why a default encoding setting would change the fontsize (to something unreadable ?) .

The other problem is that somebody on those threads said that a system reboot is required... for the registry hacks to be effective... of course a solution without a required restart would be better... but if needed we would also need to add this info/warning about the required system reboot.

We would need to search and test the best options and mention it/them within that new wiki page.

----

For the second idea:
What if we create a temporary file with an utf8 filename (even with some special windows-only API, not fopen/fwrite, if needed) to test if we could afterwards "Access" it and if this doesn't work we show a new warning message with a link to the wiki page similar to the timeout patch:
`To disable the timeout, see: https://hashcat.net/q/timeoutpatch`

maybe something like this:
`Your shell does NOT support UTF8 file names, please enable support for it with https://hashcat.net/q/winshellencoding`
(or similar)

I think this is the only valid solution. because if we just add some strange / hacky changes to our fopen () calls, it won't fix the root of the problem (because, as said above, all the libraries and OpenCL/CUDA compilers have exactly the same problem... they can't deal with UTF8 filenames if the shell doesn't allow it... and we can't change the source code of the OpenCL compilers, it's out of our reach).

What do you think.

Thank you very much

**Comment by neheb** [comment]
Detecting and warning about chcp 65001 sounds good.

**Comment by neheb** [comment]
this will never be fixed.
