### ISSUE TITLE
Feature request - increase nonce length for SIP Digest Auth

### ISSUE THREAD

**Issue by DasExperimentator** [hashcat/hashcat#1624]
I'm trying hashcat in SIP Digest Authentication (MD5). 
It works well with nonce lengths of up to 50 characters.
In my case, the nonce provided by a SIP server is 54 chars. Thus, the hashcat throws a salt-length exception:

`Hash '$sip$*': Salt-length exception`
`No hashes loaded.`

Would it be possible to expand the acceptable nonce length to 54 chars?
(Perhaps, it may even make sense to expand it slightly further, in order to have some 'spare' room, just in case...)

The example of a nonce value that's giving me the trouble is
`Nonce Value: "5df64cc15b4b2c611XFc619ca4ebc1f5c02ca2bc1db314e52423a6"`

**Comment by jsteube** [comment]
We need some example data to work with (plus password).

**Comment by philsmd** [comment]
this "problem" is similar to this recent issue: https://github.com/hashcat/hashcat/issues/1603

I also explained how to fix it (by changing the parsing code) here:
https://github.com/hashcat/hashcat/issues/1603#issuecomment-400808910


Now the question is that because we already got 2+ request for this, it might make sense to increase the maximum nonce length a little bit, e.g. to 64.

I'm still not sure why these nonces (numbers used once) are that large for some implementations. If somebody has a clue and how large they could be (or even better the average and maximum length) it would help a lot in making a good decision here. I remember reading the standard/rfc for the last issue, but I didn't really came to a good conclusion... it just seems that the "number" can also be a non-number (e.g. could have colons or other characters in it) and could be of arbitrary length.
I think a length of max 64 chars would make sense because in theory it should be a "normal" number, I guess... and therefore it should not be an extremly long arbitrary string.

**Comment by DasExperimentator** [comment]
Thanks! 
I also searched for a maximum nonce length, but I didn't find an exact answer. Moreover, from my experience, nonce is not always a number. For example, nonces from Asterisk PJSIP contain forward slashes (though, the length was still less than 50 characters in that case).

**Comment by DasExperimentator** [comment]
I am testing the fix suggested in #1603 . It seem to work fine, but there's an issue if I try to restore the session afterwards. Whenever hashcat is started with the --restore option, I get an error:
`Hash '$sip$*': Line-length exception`

**Comment by philsmd** [comment]
I could not reproduce the --restore problem: my guess is that you are doing something wrong or have old files lying around (did you do a make clean etc). Anyway, I've now pushed a fix for the esalt/nonce length limitation: https://github.com/hashcat/hashcat/pull/1631. The new limit is about 1024 bytes.

**Comment by DasExperimentator** [comment]
I just recompiled the hashcat from master. The --restore problem is still there, although now the error is different:
`Hash '$sip$*': Separator unmatched`
`No hashes loaded.`

My command to start the hashcat is:
`hashcat --session 111 -O -w 3 -a 3 -m 11400 '$sip$***1234567890*098765431*REGISTER*sip*10.10.10.10**5df64cc15b4b2c611XFc619ca4ebc1f5c02ca2bc1db314e52423a6*a39111119411168a*00000001*auth*MD5*14bfffbfe3eeeea1e2b3aaa4f16784ad'  --increment --increment-min 4   ?a?a?a?a?a?a?a?a?a?a?a?a?a`

(hashes and other data are replaced with dummy values, on purpose)

This starts the hashing normally (even with the dummy values). Then I stop it with 'c', wait until hashcat finishes, and then try to restore the session with:

`hashcat --session 111 --restore`

That's when hashcat gives me the 'Separator unmatched' error.

Am I doing something wrong?

**Comment by jsteube** [comment]
Wait there's something wrong with your installation. I've tested with exact your command and it works fine. I've even tested the restore functionality which works fine. So for me it looks you're trying to restore from an incompatible file which has been created from an older version of hashcat. I think you really need to make sure you're using the latest version of hashcat. A good sign that you're not using the latest version is that you did not use ./ in front of hashcat and eventually executed an older 2nd installation of hashcat. Maybe you used "make install" or you have another hashcat installation from your OS repostory. Anyway, not a hashcat problem here.

**Comment by philsmd** [comment]
@DasExperimentator hey, the problem with --restore should be fixed with latest code. This commit https://github.com/hashcat/hashcat/commit/cc8fa3ee8033e6258126ec17abbe476252532c5a should fix the problem of wrong hashes within the .restore file whenever the hash was a command line argument (instead of a hash file).
This problem was introduce very recently with the addition of the tokenizer within the parser. Thanks for reporting it. It seems completely unrelated with this issue and/or with SIP (but only -m 11400 = SIP used TOKEN_ATTR_TERMINATE_STRING therefore I admit it was somehow related, but just not related with the nonce/esalt problem).

Would be great if you can test the latest master code. Thx

**Comment by DasExperimentator** [comment]
@philsmd , wow! That was fast!
I just tested the latest master on a freshly installed Ubuntu 18.04 LTS. :)
Everything works perfectly fine. '--restore' worked flawlessly for the hash in a file and for the hash in a command line. I can confirm the issue is resolved.
Thanks a lot for all the help and support!!!
