### ISSUE TITLE
m22000 outfiles submission doesn't remove hashes

### ISSUE THREAD

**Issue by RealEnder** [hashcat/hashcat#2727]
When working with large m22000 hashlists/wordlists it often takes a lot of time for a job to complete. Having cracked some of the hashes may remove some salts and ease the cracking process. hashcat's way of doing that is to add cracked potfile results to [session].outfiles directory. For mode 22000 the potfile has different structure than most of the other modules hash:pass format.
Tried to add to outfiles dir cracked hashes in different forms, like original_hash, original_hash:pass, PMK*essid_hex:pass, but none of these removed the hashes during the cracking process.

**Comment by jsteube** [comment]
I think this is a bug. What we can do is to rewrite the outfile check so that it accepts the hash in its original format (input hash format). Then hashcat can find the correct hash in the in-memory database while running. That ok?

**Comment by RealEnder** [comment]
Input hash format will be OK, just we'll not have the plaintext in the potfile. This should be noted somewhere, so we'll not confuse the users.

**Comment by jsteube** [comment]
Wait, to not confuse things. The plaintext is part of the hashline in the outfile-check-dir file. The format is not the one from the potfile, but the original one. Based on this, do you still think we need to document this somewhere? Because I feel this is very natural behavior.

**Comment by RealEnder** [comment]
Oh, I misunderstood the outfile will accept *only* the input hashes format, without the plaintext. hash + plaintext is the natural behaviour and there's no need for further explanations IMO.

**Comment by jsteube** [comment]
OK, should be fixed with commit https://github.com/hashcat/hashcat/commit/e591b0039b676809b31dd4e711883d318c49e8e8

**Comment by RealEnder** [comment]
Tried with @ZerBea but still doesn't work as expected. Passed in form "22000hash:plaintext" and "22000hash*plaintext" just in case, but this wasn't added to the potfile/cracked.

**Comment by jsteube** [comment]
Wait, but that's the expected behavior. It's what we discussed. Maybe we need to restart from scratch? Please explain the problem in full.
