### ISSUE TITLE
Device memory allocation errors on SCRYPT for r power-of-2 but fine for r+1

### ISSUE THREAD

**Issue by lhunath** [hashcat/hashcat#2757]
Attacking a scrypt hash using an `N` value of `32768`, `p` value of `1` or `2`, the operation fails with:
```
* Device #1: Not enough allocatable device memory for this attack.
```
whenever the `r` value is a power-of-2 (ie. `1`, `2`, `4`, `8`), but the operation works fine for other `r` values, which should technically consume more memory (eg. `3`, `7`, `9`).

Using `CUDA API (CUDA 11.3)`, device is `NVIDIA GeForce GTX 1060 6GB 5228/6144 MB, 10MCU`, hashcat `6.1.1-229-g96c6878ef`.

Note:
This problem does not occur when running the same operation on the same machine against the same device using the `OpenCL 3.0 CUDA 11.3.55` backend instead.

**Comment by jsteube** [comment]
Now that's timing. With latest commit I had updated the SCRYPT workload tuning logic. Try again with your hash, if you receive too less memory error, try with -n 1 --force.

**Comment by lhunath** [comment]
Haha, that's bad luck, I checked the code out literally as you were writing the fix.

Looks like the above problem has been resolved with 57a8923b81a36edbd5efefb2663a93e3447f35c8 - thanks!

**Comment by lhunath** [comment]
It looks like this commit has also quadrupled my hash speed? Is that possible?

Going from:
```
hashcat (v6.1.1-229-g96c6878ef+) starting...

* Device #2: NVIDIA GeForce GTX 1060 6GB, 5440/6144 MB (1536 MB allocatable), 10MCU

Session..........: hashcat
Status...........: Quit
Hash.Name........: scrypt
Hash.Target......: SCRYPT:32768:9:2:Mzg3MjYzNzYwMzE0NDE=:uM7P3Kg2X9En9...g3o1M=
Time.Started.....: Fri Apr 16 18:50:15 2021 (1 min, 38 secs)
Time.Estimated...: Sat Apr 17 02:14:47 2021 (7 hours, 22 mins)
Guess.Mask.......: ?1?2?2 [3]
Guess.Charset....: -1 ?l?d?u,, -2 ?l?d,, -3 ?l?d*!$@_,, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:        3 H/s (49244.38ms) @ Accel:1 Loops:1 Thr:16 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 160/86247 (0.19%)
Rejected.........: 0/160 (0.00%)
Restore.Point....: 0/1369 (0.00%)
Restore.Sub.#2...: Salt:0 Amplifier:1-2 Iteration:0-1
Candidates.#2....: mar -> mna
Hardware.Mon.#2..: Temp: 72c Fan: 37% Util:100% Core:1873MHz Mem:3802MHz Bus:16
```
to
```
hashcat (v6.1.1-230-g57a8923b8+) starting...

* Device #2: NVIDIA GeForce GTX 1060 6GB, 5440/6144 MB (1536 MB allocatable), 10MCU

Session..........: hashcat
Status...........: Quit
Hash.Name........: scrypt
Hash.Target......: SCRYPT:32768:9:2:Mzg3MjYzNzYwMzE0NDE=:uM7P3Kg2X9En9...g3o1M=
Time.Started.....: Fri Apr 16 20:22:07 2021 (45 secs)
Time.Estimated...: Fri Apr 16 21:12:57 2021 (50 mins, 5 secs)
Guess.Mask.......: ?1?2?2 [3]
Guess.Charset....: -1 ?l?d?u,, -2 ?l?d,, -3 ?l?d*!$@_,, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:       28 H/s (11285.56ms) @ Accel:10 Loops:1 Thr:32 Vec:1
Recovered........: 0/1 (0.00%) Digests
Progress.........: 960/86247 (1.11%)
Rejected.........: 0/960 (0.00%)
Restore.Point....: 0/1369 (0.00%)
Restore.Sub.#2...: Salt:0 Amplifier:3-4 Iteration:0-1
Candidates.#2....: car -> ccl
Hardware.Mon.#2..: Temp: 72c Fan: 30% Util:100% Core:1873MHz Mem:3802MHz Bus:16
```

**Comment by jsteube** [comment]
Yes and no. The SCRYPT autotune logic didn't receive much love before. If you'd hand tuned the -n, -u and -T you'd have resulted in the same performance. It's possible it's still not at the top speed, a description on how to find out follows soon.

**Comment by lhunath** [comment]
I assume that also means there's not much credence in comparing against people's previous scrypt hashcat benchmark results such as https://gist.github.com/epixoip/ace60d09981be09544fdd35005051505.

**Comment by lhunath** [comment]
Running the hashcat benchmark now fails:
```
$ ./hashcat.exe -m 8900 -b
hashcat (v6.1.1-230-g57a8923b8+) starting...

CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce GTX 1060 6GB, 5228/6144 MB, 10MCU

OpenCL API (OpenCL 3.0 CUDA 11.3.55) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce GTX 1060 6GB, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Segmentation fault
```

`gdb` run:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff8bcc8d2f1 in strlen () from /cygdrive/c/WINDOWS/System32/msvcrt.dll
(gdb) bt
#0  0x00007ff8bcc8d2f1 in strlen () from /cygdrive/c/WINDOWS/System32/msvcrt.dll
#1  0x0000000000406871 in ?? ()
#2  0x00000000004045f6 in ?? ()
#3  0x0000000000405052 in ?? ()
#4  0x00000000004b9426 in ?? ()
#5  0x00000000004013c7 in ?? ()
#6  0x00000000004014fb in ?? ()
#7  0x00007ff8bcb87034 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/WINDOWS/System32/KERNEL32.DLL
#8  0x00007ff8bd662651 in ntdll!RtlUserThreadStart () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Have to figure out how to build with debug symbols still...

**Comment by jsteube** [comment]
> I assume that also means there's not much credence in comparing against people's previous scrypt hashcat benchmark results such as https://gist.github.com/epixoip/ace60d09981be09544fdd35005051505.

yeah, they are outdated now

**Comment by jsteube** [comment]
There's DEBUG flag in src/Makefile

**Comment by lhunath** [comment]
Looks like the segfault went away as a result of rebuilding, maybe because I did `make clean`.

That said, benchmarking still gives me:
```
$ ./hashcat.exe -m 8900 -b
hashcat (v6.1.1-230-g57a8923b8+) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

CUDA API (CUDA 11.3)
====================
* Device #1: NVIDIA GeForce GTX 1060 6GB, 5228/6144 MB, 10MCU

OpenCL API (OpenCL 3.0 CUDA 11.3.55) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce GTX 1060 6GB, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 8900 - scrypt (Iterations: 1)

* Device #1: Not enough allocatable device memory for this attack.

Started: Fri Apr 16 20:53:25 2021
Stopped: Fri Apr 16 20:53:48 2021
```

Manually using `-n1 --force` as you suggested solves that.

**Comment by jsteube** [comment]
I think -n 9, 18 or 36 should give nice results.

**Comment by lhunath** [comment]
Thanks. I assume the benchmark mode shouldn't just fail without `--force`, though, right?

As an aside, could I ask if it's safe to assume that if a `1080 Ti`'s old scrypt benchmarks (as linked) are 3x faster than my `1060` benchmarks (before your change), that a `1080 Ti`'s scrypt performance after your change will also be 3x that of mine after your change? And could I assume that 3x applies across the board in terms of N,r,p, more or less?

**Comment by jsteube** [comment]
With the benchmark for -m 8900 you can't compare it anymore because I changed the configuration for the scrypt hash in the benchmark from 1024:1:1 to 16384:8:1. You could use -m 22700 in the old benchmark as reference, it had the 16k:8:1

**Comment by lhunath** [comment]
Yeah, I saw that.  But if I make sure that the scrypt parameters stay the same (1024:1:1) when I find the 3x, is it safe to say "a 1080 Ti is just 3x faster at scrypt than a 1060", even at different parameters (eg. 16384:8:1)?

**Comment by jsteube** [comment]
I can't either say yes or no.

**Comment by jsteube** [comment]
Check this out: https://github.com/hashcat/hashcat/commit/b9604b6f2260677c2a95f5ade30d50743231efdc

**Comment by lhunath** [comment]
Excellent explanation!

**Comment by lhunath** [comment]
> That said, benchmarking still gives me:
> 
> ```
> $ ./hashcat.exe -m 8900 -b
> hashcat (v6.1.1-230-g57a8923b8+) starting in benchmark mode...
> 
> CUDA API (CUDA 11.3)
> ====================
> * Device #1: NVIDIA GeForce GTX 1060 6GB, 5228/6144 MB, 10MCU
> 
> * Device #1: Not enough allocatable device memory for this attack.
> ```
> 
> Manually using `-n1 --force` as you suggested solves that.

How come scrypt-tmto doesn't automatically come in to save me here?

**Comment by jsteube** [comment]
It's a legitimate question, because this doesn't really is what is expected. I believe (I have to guess because it's not happing to me) it's because you have reserved much more extra space than expected. Most people run hashcat on headless servers. 

There's no "clean" solutions to this other than to increase a fixed size limit, but this can lead to slower cracking speed because hashcat allocates less memory than it could. In the end it goes back to CUDA and OpenCL which both do not report the correct remaining (free) memory so we add some extra buffer.

If you want to check it out if it solves the problem, find this line src/backend.c

```
EXTRA_SPACE = MAX (EXTRA_SPACE, (  64ULL * 1024ULL * 1024ULL));
```

Replace 64 with 256 or so.

**Comment by jsteube** [comment]
Please retry with latest version from GitHub master and close the issue if fixed.

**Comment by lhunath** [comment]
Looks good now.
