### ISSUE TITLE
Kernel ./OpenCL/m17220_a3-pure.cl build failed

### ISSUE THREAD

**Issue by chen-pi-2007** [hashcat/hashcat#4482]
**I'm really sorry, I've been trying to solve this error for a long time, 

D:\tool\hashcat-7.1.2>hashcat.exe -m 17220 -a 3 F:\aaa\text\2024case1\hash.txt
hashcat (v7.1.2) starting

CUDA API (CUDA 13.0)
====================
* Device #01: NVIDIA GeForce RTX 5070, 10929/12226 MB, 48MCU

OpenCL API (OpenCL 3.0 CUDA 13.0.84) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #02: NVIDIA GeForce RTX 5070, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256
Minimum salt length supported by kernel: 0
Maximum salt length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Not-Iterated
* Single-Hash
* Single-Salt
* Brute-Force

Watchdog: Temperature abort trigger set to 90c

nvrtcCompileProgram(): NVRTC_ERROR_COMPILATION

main_kernel(93): catastrophic error: cannot open source file "OpenCL/inc_checksum_crc32.cl"
  #include M2S(INCLUDE_PATH/inc_checksum_crc32.cl)
                                                  ^

1 catastrophic error detected in the compilation of "main_kernel".
Compilation terminated.

* Device #1: Kernel ./OpenCL/m17220_a3-pure.cl build failed.

* Device #1: Kernel ./OpenCL/m17220_a3-pure.cl build failed.

Started: Tue Sep 09 16:15:43 2025
Stopped: Tue Sep 09 16:15:43 2025

**Comment by matrix** [comment]
fixed by #4463

**Comment by chen-pi-2007** [comment]
> 由 [#4463](https://github.com/hashcat/hashcat/pull/4463) 修复

I used the latest version of hashcat-7.1.2, but I still encountered this problem... so I really don't know what to do.

**Comment by chen-pi-2007** [comment]
> [由#4463](https://github.com/hashcat/hashcat/pull/4463)修复[](https://github.com/hashcat/hashcat/pull/4463)

The problem is solved. The content in OpenCL in the Grand Prize source code has replaced the original file.

**Comment by matrix** [comment]
> > 由 [#4463](https://github.com/hashcat/hashcat/pull/4463) 修复
> 
> I used the latest version of hashcat-7.1.2, but I still encountered this problem... so I really don't know what to do.

The fix will be included in the next official release. In the meantime, you have two options: pull code from github to builde an updated version or use a beta version (https://hashcat.net/beta/).
